### ISSUE TITLE
Find a way to override the user and group for NGINX

### ISSUE THREAD

**Issue by dminca** [dminca/drupal-docker#34]
`/app/sites` needs to be `chmod nginx:nginx` and if the user and group doesn't exist, the build will fail.

* create the `nginx` user and group
* use the default HOST `$USER` and group

#### How to start
You can start just by launching the containers via the `docker-compose` and inject the host `$USER` via the `docker-compose.yml` just like this:
```yml
web:
  image: completit/dockerized-drupal:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./app:/var/www/html
  environment:
    - USER=${USER}
  links:
    - psql
```

#### Useful resources
- [Nginx boilerplate - sample configs][1]
- [Docker compose officially supports env vars][2]

**Relates to** #39 

[1]: https://github.com/nginx-boilerplate/nginx-boilerplate
[2]: https://docs.docker.com/compose/environment-variables/
