### ISSUE TITLE
Make the Nginx user and group name dynamic

### ISSUE THREAD

**Issue by dminca** [dminca/drupal-docker#39]
- [x] update README with [official docker nginx alpine image documentation](https://hub.docker.com/_/nginx/)
- [ ] make the `user  nginx` [directive][1] dynamic (relates to: #34 )

* Consider using the image, and add PHP 7 in the container. 
* If using the base `nginx:stable-alpine` docker image, PHP must be downgraded as that image doesn't support PHP 7. 
* The [minimum system requirement][2] is **PHP 5.5.9 or higher** and **Alpine 3.3** supports minimum [**PHP 5.6.21-r0**][3]
* ~~If PHP 7 is not supported, just include it by adding `echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories` to the `Dockerfile`~~ **[NOT SUPPORTED]** by Alpine 3.3

## The purpose
> to use environment variables in nginx configuration

Out-of-the-box, Nginx doesn't support using environment variables inside most configuration blocks. But `envsubst` may be used as a workaround if you need to generate your nginx configuration dynamically before nginx starts.

Here is an example using docker-compose.yml:
```yml
  image: nginx
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```
The mysite.template file may then contain variable references like this :
```nginx
listen ${NGINX_PORT};
```

### envsubst on Alpine Linux
As discussed in the official [Alpine Linux IRC][4] channel, `envsubst` is found in `/usr/bin/envsubst is owned by gettext-0.19.7-r3` , and can be used after `apk add gettext`. **THE COOLEST ALPINE LINUX** community from iRC! :tada: :confetti_ball:
>
```
(17:10:41) darkfader: dminca: you can open a package request for it
(17:10:49) darkfader: sounds like an easy to build package in that case
(17:10:52) kl3:  $ apk info --who-owns $(which envsubst)
(17:10:53) kl3: /usr/bin/envsubst is owned by gettext-0.19.7-r3
(17:10:56) darkfader: or
(17:10:59) darkfader: that :)
(17:11:23) dminca: awesome kl3 darkfader , thanks guys :)
(17:12:07) dminca: and how can I install it from other source?
(17:12:15) kl3: dminca: You're welcome.
(17:12:18) dminca: apk add ... ?
(17:13:03) kl3: gettext is in the main repo, just do 'apk add gettext'
(17:13:39) dminca: yay ! I got envsubst, thank you kl3 :D
```

# What will this solve?
This way, we won't need to `chown -R nginx:nginx app` so it will close #45 

[1]: http://nginx.org/en/docs/ngx_core_module.html#user
[2]: https://www.drupal.org/requirements
[3]: https://pkgs.alpinelinux.org/packages?page=1&branch=v3%2E3&name=php%2A
[4]: http://wiki.alpinelinux.org/wiki/Alpine_Linux:IRC
